- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone https://github.com/pekkosams/ami-feedbacker && \
    cd ami-feedbacker && \
    git checkout PROD && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > ami-feedbacker/kubernetes.yaml


- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd ami-feedbacker && \
    git add kubernetes.yaml && \
    git commit -m "Deploying image gcr.io/${PROJECT_ID}/ami-feedbacker:${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository ami-feedbacker
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin candidate
